### ISSUE TITLE
Table top_block_info is not updated.

### ISSUE THREAD

**Issue by stepanLav** [MBoldyrev/iroha#1]
**Environment:** 
LOCAL
MacOS
**Version**
*Branch:* feature/keep-wsv-data
*Commit:* 2e114277cd52eee1a216feb63a9302d97a3f2526
*Settings:*
[settings.zip](https://github.com/MBoldyrev/iroha/files/4218882/settings.zip)

**Detail description:**
When a new block is commit, the table "top_block_info" is not updated.

*Scenario:*

1. Start new network of iroha containing one node
2. Check database - in the table "top_block_info" added entry
3. Send some transaction to Iroha, until the height of the block chain changes.
4. Check database - table "top_block_info"

**Expected result:**
Table "top_block_info" updated after every new block committed
**Actual result:**
Table "top_block_info" don't update

Log:
[iroha_log.txt](https://github.com/MBoldyrev/iroha/files/4218907/iroha_log.txt)

That's why the node won't start again with --reuse_state. 

[Irohad/Storage/MutableStorageImpl]: Applying block: height 2, hash acee50a0a28cb1772cac8b0690eda643e0468b2840651ea5b3818222afd2ab1e
[critical][Init]: Irohad startup failed: Cannot apply block!

<details>
  <summary>BD screen!</summary>

![image](https://user-images.githubusercontent.com/40560660/74732093-83345280-525a-11ea-95c5-b65bc0078568.png)
</details>

**Comment by MBoldyrev** [comment]
thanks! this happens because I did not cover the case of enabled prepared blocks. will fix it soon.

**Comment by MBoldyrev** [comment]
must be fixed in 2b654e75d and tested in 13b9da3dc
@stlavr please confirm the fix

**Comment by stepanLav** [comment]
**Status verification:**   Successful
